<?php

namespace FROG\CooperativeBankSdk;

class CoopUtils
{
    /**
     * Generates a unique reference to a request being made to the API
     * 
     * @return string a random string generated by the random_bytes function
     */
    static function generate_message_reference(): string
    {
        $bytes = random_bytes(19);
        return substr(strtr(base64_encode($bytes), '+/', '-_'), 0, 19);
    }
}
